dbCredential:
#  db_Server_IP_Address: 10.10.10.62
  db_Server_IP_Address: localhost
  userName: root
  password: admin
  database: contentschema
  url: jdbc:mysql://localhost:3306/contentschema
  driver: com.mysql.jdbc.Driver

server:
  applicationConnectors:
    - type: http
      port: 7777
  adminConnectors:
    - type: http
      port: 7778

